- BUILD
- tor-droid-make.sh
It is used to help the developer to fetch and build the app.
Initially, three commands were add:
1. fetch: It fetches the external dependencies
2. build: Build the project in release or debug mode
> Add android tor build script

- external/Makefile
Follow up for #11
Fixes build for me:
https://travis-ci.org/Unpublished/tor-android/builds/502182296 (search for `error: cannot find -lssl` -> https://travis-ci.org/Unpublished/tor-android/builds/502297720
> use --disable-samples introduced in libevent 2.1.5

- external/Makefile
This includes the three new techniques for making the binaries smaller:
* exclude the directory authority module
* exclude unused features in the openssl build
* build using `-Os` rather than `-O2` to optimize for file size
https://trac.torproject.org/projects/tor/ticket/32200
closes #18 
The test build run is here:
https://gitlab.com/eighthave/tor-android/pipelines/95692178
@n8fr8 @sisbell @sysrqb
> smaller binaries

- README
Update Wiki FAQ link to non-obsolete FAQ; Update torproject.org link to non-404.
> fix(README): Broken/obsolete FAQ links

- tor-android-binary/src/main/java/org/torproject/jni/TorService.java
This crashes Android devices by filling up the data partition
with a huge log file.
> Do not always send debug logging to file

- sampletorapp/build.gradle
- sampletorapp/src/main/java/org/torproject/android/sample/GenericWebViewClient.java
- sampletorapp/src/main/java/org/torproject/android/sample/MainActivity.java
- sampletorapp/src/main/res/layout/activity_main.xml
The sample app in this project has always been very barebones, but I noticed it wasn't kept up to date and wasn't working at all.
The first commit here gets the project to build on a fresh clone of this repository. The second gets the app running again, while updating libraries to latest tor-android, and generally updating the app's code to look like a more modern Android app.
This commit is the bare minimum to get it working again.
> Sample App Works

- build.gradle
- sampletorapp/src/main/AndroidManifest.xml
- tor-android-binary/build.gradle
- tor-android-binary/src/androidTest/java/org/torproject/jni/TorServiceDoubleUnbindTest.java
- tor-android-binary/src/androidTest/java/org/torproject/jni/TorServiceTest.java
- tor-android-binary/src/main/java/org/torproject/jni/TorService.java
This PR prevents the crashes seen in ~~#57 and~~ [Tor #32729](https://gitlab.torproject.org/tpo/core/tor/-/issues/32729) by preventing concurrent calls to the Tor API. Concurrent calls are prevented in two ways:
1. Move the call to mainConfigurationFree() onto the same thread as runMain() to ensure it's never called before runMain() has returned, per the comments in tor_api.h.
2. Use a static lock to prevent different TorService instances within the same process from making concurrent native calls. It was previously possible for this to happen because the native calls are made from a background thread that may (briefly) outlive the TorService instance that launched it.
Edit: The crashes seen in #57 seem to be caused by file descriptor reuse and are not fixed by this PR.
> Prevent concurrent calls to Tor API

- tor-android-binary/src/main/java/org/torproject/jni/TorService.java
This unnests the try/finally block that was added in pull #59, and moves it to the main try block, where it now handles the whole shutdown procedure.
* https://github.com/guardianproject/tor-android/pull/61#discussion_r766016252
* https://github.com/guardianproject/tor-android/issues/57
* https://github.com/guardianproject/tor-android/pull/59
@grote @akwizgran 
The intention of this is probably easier to see when the diff starts from before 09de98ddcd86ca60eb0c2d3ed891c90a69b04b57 in #59:
```diff
--- a/tor-android-binary/src/main/java/org/torproject/jni/TorService.java
+++ b/tor-android-binary/src/main/java/org/torproject/jni/TorService.java
@@ -7,6 +7,7 @@ import android.os.Binder;
import android.os.FileObserver;
import android.os.IBinder;
import android.os.Process;
+import …
```
> ensure TorService properly shuts down whenever the tor thread stops

- tor-android-binary/src/main/java/org/torproject/jni/TorService.java
Most apps that use TorService as a library do not want to share the tor instance with other apps.  So TorService should not send global broadcasts in that case.  Apps like Orbot and TorServices still need to send global broadcasts, so there is a method to re-enable that.
@grote @akwizgran As a follow-on to the issues raised in #71.
@n8fr8 @bitmold is this change OK for Orbot?
> default to broadcasting to the current app only, with opt-in global

- tor-android-binary/src/main/java/org/torproject/jni/TorService.java
Based on this discussion:
https://github.com/guardianproject/tor-android/issues/67#issuecomment-1043258065#67
CI is here:
https://gitlab.com/eighthave/tor-android/-/pipelines/522792599
> use "volatile" for key variables that are accessed across threads

- sampletorapp/src/main/java/org/torproject/android/sample/MainActivity.java
- tor-android-binary/src/main/java/org/torproject/jni/TorService.java
This enables people to set these values from their torrc. Setting these options as command line args prevents any users of tor-android to configure these properties differently. I tried to preserve all default behavior by providing sensible defaults in the event that the user does not set them. 
This also fixes #79 
This is needed to fix a range of Orbot issues: 
- https://github.com/guardianproject/orbot/issues/709
- https://github.com/guardianproject/orbot/issues/708
- https://github.com/guardianproject/orbot/issues/707
- https://github.com/guardianproject/orbot/issues/317
> Removes SOCKS/HTTP Proxy Hardcoding 

- external/Makefile
The latest NDK 25 produces a flood of macro redefined warnings when building openssl.
Example:
```
<command line>:23:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 21
^
<built-in>:362:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
^
```
> Remove macro redefined warnings for openssl

- README.md
- build.gradle
zlib is chosen by tor before xz and zstd, so lets update to latest bugfix release tag.
> Zlib update

- .gitlab-ci.yml
Running builds in vagrant container was failing for me because building xz now apparently needs po4a (a translation tool) for successfully running builds.  This change installs the dependency with apt, into both gitlab-CI and vagrant build environments.
Here's the relevant output of `./tor-droid-make.sh release -f`:
```
+ sh update-po
po4a/update-po: The program 'po4a' was not found.
po4a/update-po: Translated man pages were not generated.
make: *** [Makefile:200: xz/Makefile] Error 1
make: Leaving directory '/builds/guardianproject/tor-android/external'
```
> 🐛 add missing tool (po4a) to ci script

- gradle/wrapper/gradle-wrapper.properties
It seems the graldew was updated without updating the download checksum in gradle-wrapper.properties. This breaks the build automation in gitlab CI and vagrant. (The correct checksum can be looked up here: https://gradle.org/release-checksums/#v7.4 )
Here's the error message I got when trying to run `tor-droid-make.sh release -f` in vagrant without this change:
```
Downloading https://services.gradle.org/distributions/gradle-7.4-all.zip
...............................................................................................................
........................................
Verification of Gradle distribution failed!
Your Gradle distribution may have been tampered with.
Confirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you …
```
> 🐢 update gradlew hash

- .gitmodules
- external/Makefile
- external/build-tools
- tor-droid-make.sh
Fixes warning on Android devices running API <= 25:
WARNING: linker: /data/app/org.torproject.android-1/lib/arm64/libtor.so: unsupported flags DT_FLAGS_1=0x8000001
> Add elf-cleaner to clean unwanted ELF flags

- tor-android-binary/build.gradle
Updating to NDK 25+ requires minSDK 19.  Be consistent with the other build.gradle configurations.
> NDK 25+ requires minSDK 19

- external/Makefile
Tor 0.4.8 requires enabling gpl code to enable new pow defense system.
> Enable GPL code for PoW Defense

- build.gradle
Tor 0.4.8.7 version code should be 4807 because it needs to be a lower number when Tor 0.4.8.10 is released (4810).
> Fix version code incrementation

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- tor-android-binary/build.gradle
Update to latest stable gradle which includes fixes for CVE-2022-36033 and specify updated build tools made to support SDK 33.
> Update to gradle 7.6.3 and latest stable AGP

- external/Makefile
and adds to compile time + binary size. Tor Browser disables this module on Android but also on all other platforms.
> Add --disable-openssl to libevent build stamp. It's not needed for tor

- .gitlab-ci.yml
- .gitmodules
- BUILD.md
- external/Makefile
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/34202
We should be fine with zlib and zstd. This should reduce compile time, code/repository complexity and binary size.
> Remove lzma/xz from tor-android 

- external/Makefile
This change fixes the lzma build issue for me. After applying this change, I reccomend running a full clean before building:
```
./tor-droid-make.sh fetch -c && ./tor-droid-make.sh build
```
> 🐞 fix lzma issue

- tor-android-binary/build.gradle.kts
- tor-droid-make.sh
The build script tor-droid-make.sh fails when building a release because sourcesJar is now undefined.
fixes #165
> Add sourcesJar task to fix build script

- external/Makefile
NDK_TOOLCHAIN has not been used since NDK 21.
> Remove unused NDK_TOOLCHAIN references in Makefile
